# Generated by Django 4.2.5 on 2023-09-21 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_usuarios'),
    ]

    operations = [
        migrations.DeleteModel(
            name='usuarios',
        ),
    ]
