# Generated by Django 4.2.5 on 2023-09-21 01:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_delete_usuarios'),
    ]

    operations = [
        migrations.CreateModel(
            name='viagens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=250)),
                ('endereco', models.CharField(max_length=70)),
                ('cidade', models.CharField(max_length=50)),
                ('data_inicial', models.DateField(default=datetime.datetime(2023, 9, 21, 1, 8, 5, 564014, tzinfo=datetime.timezone.utc))),
                ('data_final', models.DateField(default=datetime.datetime(2023, 9, 21, 1, 8, 5, 564014, tzinfo=datetime.timezone.utc))),
                ('categoriafk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoria', to='main.categoria_viagem')),
            ],
        ),
    ]
