# Generated by Django 4.2.5 on 2023-09-21 01:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_viagens'),
    ]

    operations = [
        migrations.AddField(
            model_name='viagens',
            name='valor_diaria',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='viagens',
            name='data_final',
            field=models.DateField(default=datetime.datetime(2023, 9, 21, 1, 14, 3, 787618, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='viagens',
            name='data_inicial',
            field=models.DateField(default=datetime.datetime(2023, 9, 21, 1, 14, 3, 787618, tzinfo=datetime.timezone.utc)),
        ),
    ]
