# Generated by Django 4.2.5 on 2023-09-21 01:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_viagens_valor_diaria_alter_viagens_data_final_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('telefone', models.CharField(max_length=12)),
                ('cpf', models.CharField(max_length=11)),
            ],
        ),
        migrations.AlterField(
            model_name='viagens',
            name='data_final',
            field=models.DateField(default=datetime.datetime(2023, 9, 21, 1, 18, 38, 197170, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='viagens',
            name='data_inicial',
            field=models.DateField(default=datetime.datetime(2023, 9, 21, 1, 18, 38, 197170, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='reservas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=datetime.datetime(2023, 9, 21, 1, 18, 38, 197170, tzinfo=datetime.timezone.utc))),
                ('valor_final', models.DecimalField(decimal_places=2, max_digits=10)),
                ('usuariofk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viagem', to='main.usuarios')),
                ('viagemfk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viagem', to='main.viagens')),
            ],
        ),
        migrations.CreateModel(
            name='fotos_viagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=200)),
                ('viagemfk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viagemfk', to='main.viagens')),
            ],
        ),
    ]
