# Generated by Django 4.2.5 on 2023-09-21 01:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_usuarios_alter_viagens_data_final_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservas',
            name='data',
            field=models.DateField(default=datetime.datetime(2023, 9, 21, 1, 19, 56, 807471, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='viagens',
            name='data_final',
            field=models.DateField(default=datetime.datetime(2023, 9, 21, 1, 19, 56, 807471, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='viagens',
            name='data_inicial',
            field=models.DateField(default=datetime.datetime(2023, 9, 21, 1, 19, 56, 807471, tzinfo=datetime.timezone.utc)),
        ),
    ]
