# Generated by Django 4.2.5 on 2023-09-21 01:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_reservas_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservas',
            name='quant_pessoas',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='reservas',
            name='data',
            field=models.DateField(default=datetime.datetime(2023, 9, 21, 1, 26, 57, 359837, tzinfo=datetime.timezone.utc)),
        ),
    ]
