# Generated by Django 4.2.5 on 2023-09-27 23:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_reservas_quant_pessoas_alter_reservas_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='categoria_pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='reservas',
            name='animal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='viagens',
            name='qtd_dias',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='reservas',
            name='data',
            field=models.DateField(default=datetime.datetime(2023, 9, 27, 23, 19, 28, 327437, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='reservas',
            name='usuariofk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to='main.usuarios'),
        ),
        migrations.CreateModel(
            name='pagamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dados', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovada', 'Aprovada'), ('recusada', 'Recusada')], max_length=50)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoria_pag', to='main.categoria_pagamento')),
                ('usuariofk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuariofk', to='main.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='nota_reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField()),
                ('reservafk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserva', to='main.reservas')),
            ],
        ),
        migrations.CreateModel(
            name='comentarios_reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(max_length=250)),
                ('reservafk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservafk', to='main.reservas')),
            ],
        ),
    ]
