# Generated by Django 4.2.5 on 2023-09-27 23:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_categoria_pagamento_reservas_animal_viagens_qtd_dias_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservas',
            name='data',
            field=models.DateField(default=datetime.datetime(2023, 9, 27, 23, 44, 34, 692208, tzinfo=datetime.timezone.utc)),
        ),
    ]
